## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  #- osx
julia:
  - 0.6
  #- nightly
notifications:
  email: false
git:
  depth: 99999999
addons:
  apt_packages:
    - lmodern
    - fonts-dejavu
    - ttf-ubuntu-font-family
    - texlive-luatex
    - texlive-xetex
    - texlive-latex-extra
    - pgf
    - pdf2svg
    - libgdbm3
#matrix:
#  allow_failures:
#  - julia: nightly

after_success:
  # generate documentation
  #- mkdir ~/.fonts
  #- cp ~/.julia/v0.6/ThinkJulia/fonts/* ~/.fonts
  #- cp ~/.julia/v0.7/ThinkJulia/fonts/* ~/.fonts
  #- luaotfload-tool --update
  - julia -e 'cd(Pkg.dir("ThinkJulia")); Pkg.clone("https://github.com/BenLauwens/GDBM.jl.git"); include(joinpath("docs", "make.jl"))'
